[package]
name = "prpl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.14", features = ["derive"] }
prettyplease = "0.2.6"
syn = { version = "2.0.18", default-features = false, features = ["full", "parsing"] }
